import type { NextPage } from "next";
import Head from "next/head";
import { HomeIcon } from "@heroicons/react/solid";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="group flex flex-col items-center cursor-pointer  w-12 sm:w-20 hover:text-white">
        <HomeIcon className="h-8 mb-1 group-hover:animate-bounce" />
        <p className="opacity-0 group-hover:opacity-100 tracking-widest">
          Home Icon
        </p>
      </div>
    </div>
  );
};

export default Home;
